version: 2
registries:
  ssrf-aws-metadata:
    type: npm-registry
    url: http://169.254.169.254/latest/meta-data/
    token: test
  ssrf-localhost:
    type: npm-registry
    url: http://localhost:9292/
    token: test
  ssrf-ipv6-mapped:
    type: npm-registry
    url: http://[::ffff:169.254.169.254]/
    token: test
  ssrf-docker-internal:
    type: docker-registry
    url: http://169.254.169.254/latest/meta-data/
    username: test
    password: test
  ssrf-gopher:
    type: npm-registry
    url: gopher://127.0.0.1:6379/_INFO
    token: test
  ssrf-file:
    type: npm-registry
    url: file:///etc/passwd
    token: test
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - ssrf-aws-metadata
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - ssrf-docker-internal
